### ISSUE TITLE
 memory leaks question

### ISSUE THREAD

**Issue by keyxuliang** [PBfordev/wxopencvtest#3]
Have you solved it yet?

**Comment by PBfordev** [comment]
No, I have not resolved the issue. Just to make sure, I want to reiterate that I think that the issue is not in my code, just this is enough to manifest it (wxWidgets GIT master, OpenCV 4.10 x64, MSVS 2022):
```cpp
#include <wx/wx.h>
#include <opencv2/opencv.hpp>

class MyApp : public wxApp
{
    bool OnInit() override
    {
        cv::Mat m;
        return false;
    }
}; wxIMPLEMENT_APP(MyApp);
```
